#!/usr/bin/env python3
"""
Auto-calculates seasonal AVGnow values for ES, US30, and NAS100
using historical ETF data (SPY, DIA, QQQ).
Saves to seasonal_data.json → regenerated by generate_seasonal_html.py
Runs daily via sync_journal.sh — fully automated.
"""
import json
import calendar
from pathlib import Path
from datetime import date

BOT  = Path.home() / "tradelocker-bot"
DATA = BOT / "seasonal_data.json"

try:
    import yfinance as yf
except ImportError:
    print("❌  yfinance not installed. Run: pip3 install yfinance --break-system-packages")
    raise SystemExit(1)

today    = date.today()
YEAR     = today.year
MONTH    = today.month
LOOKBACK = 10

INSTRUMENTS = {
    "ES":    {"ticker": "SPY",  "label": "S&P 500 / ES"},
    "US30":  {"ticker": "DIA",  "label": "US30 / Dow"},
    "NAS100":{"ticker": "QQQ",  "label": "NAS100 / Nasdaq"},
}

start = date(YEAR - LOOKBACK, 1, 1).isoformat()
end   = today.isoformat()
_, days_in_month = calendar.monthrange(YEAR, MONTH)

def calc_seasonal(ticker_sym):
    ticker = yf.Ticker(ticker_sym)
    df = ticker.history(start=start, end=end, interval="1d", auto_adjust=True)
    if df.empty:
        return {}
    df["pct"] = df["Close"].pct_change() * 100
    df = df.dropna(subset=["pct"])
    df.index = df.index.tz_localize(None) if df.index.tz is not None else df.index
    df["month"] = df.index.month
    df["dom"]   = df.index.day
    df["year"]  = df.index.year

    result = {}
    for d in range(1, days_in_month + 1):
        if date(YEAR, MONTH, d).weekday() >= 5:
            continue
        mask = (df["month"] == MONTH) & (df["dom"].between(d-1, d+1)) & (df["year"] < YEAR)
        matches = df[mask]
        if len(matches) < 3:
            mask = (df["month"] == MONTH) & (df["dom"].between(d-2, d+2)) & (df["year"] < YEAR)
            matches = df[mask]
        result[d] = round(float(matches["pct"].mean()), 2) if len(matches) > 0 else 0.0
    return result

all_data = {}
for key, info in INSTRUMENTS.items():
    print(f"Fetching {info['label']} ({info['ticker']})...")
    days = calc_seasonal(info["ticker"])
    all_data[key] = days
    month_name = today.strftime("%B")
    for d, v in sorted(days.items()):
        arrow = "▲" if v > 0.2 else "▼" if v < -0.2 else "→"
        today_tag = " ◀" if d == today.day else ""
        print(f"  {month_name[:3]} {d:2d}: {v:+.2f}% {arrow}{today_tag}")

output = {
    "year":    YEAR,
    "month":   MONTH,
    "updated": today.isoformat(),
    "source":  f"Auto-calculated from SPY/DIA/QQQ {LOOKBACK}yr history via yfinance",
    "instruments": {
        key: {str(k): v for k, v in sorted(days.items())}
        for key, days in all_data.items()
    },
    # Keep legacy key for backwards compat
    "trading_days": {str(k): v for k, v in sorted(all_data["ES"].items())}
}

DATA.write_text(json.dumps(output, indent=2))
print(f"\n✅  Saved all 3 instruments → {DATA.name}")
